# Generated by Django 3.2.13 on 2025-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptestforadminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='author',
            name='mail',
            field=models.EmailField(default='no@mails.gov', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='xTimesTwo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='nb_selled_books',
            field=models.IntegerField(default=0),
        ),
    ]
