# Generated by Django 3.2.13 on 2025-04-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptestforadminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='author',
            name='mail',
            field=models.EmailField(default='no@mails.gov', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='author',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='xTimesTwo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='nb_selled_books',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('overall_note', models.IntegerField()),
                ('reviewed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptestforadminpanel.book')),
            ],
        ),
        migrations.CreateModel(
            name='RelationBookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='', max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptestforadminpanel.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptestforadminpanel.genre')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='linked_books',
            field=models.ManyToManyField(through='apptestforadminpanel.RelationBookGenre', to='apptestforadminpanel.Book'),
        ),
    ]
