# Generated by Django 3.2.13 on 2025-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptestforadminpanel', '0002_auto_20250409_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='xTimesTwo',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
