# Generated by Django 3.2.13 on 2025-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptestforadminpanel', '0003_alter_author_xtimestwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='xTimesTwo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linked_books', models.ManyToManyField(to='apptestforadminpanel.Book')),
            ],
        ),
    ]
